### PR TITLE
 April 2022 topics list

### PR DESCRIPTION
**Pull request by DanGould**
To contribute topics or improve the topics list, please either (1) make comments on this PR or (2) open a PR against this branch with your changes. You can also raise suggestions by [Tweeting](https://twitter.com/TaiwanBitdevs) at us

### CODE REVIEW

**Comment by DanGould** [comment]
[Pricing liquidity for Lightning wallets](https://github.com/GaloyMoney/liquidity-fees-paper)[](https://eprint.iacr.org/2021/1287.pdf)

    Credit: José I. Rojas Echenique & Nicolas Burtey
    “The possibility of liquidity arbitrage on the Lightning network sets a market rate for inbound liquidity.”

[Block (formerly Square) Hardware Wallet Update: Fingerprints, batteries and people](https://wallet.build/march-update/)

    Credit: Block
    “We believe PINs, passwords, and seed phrases are confusing and often not secure given the workarounds normal people have to create given all the friction.”
    [How the wallet we're building works](https://wallet.build/how-the-wallet-works/)
    "we are designing for people who will have a lot to learn – about bitcoin, wallets, and the technology they need to use for both."

BIP21 is a no brainer - At the moment there is a massive UX hurdle that exists for users of different bitcoin wallet software providers.

    Credit: Marty Bent
    “Asking users to choose between on-chain and lightning payments can be confusing - but it’s been necessary to maintain interoperability between wallets”
    https://github.com/sbddesign/bip21-site/issues/47#issuecomment-1074691789 By Christopher Allen

[Bitcoin Bounties hub](https://bitcoinbounties.org/)

    Credit: Coinkite

(thanks for this list ChicagoBitdevs ;))

new software releases:

sensei v2
https://github.com/L2-Technology/sensei/releases/tag/v0.0.2

**Comment by louihliu** [comment]
[Lightning Taro](https://lightning.engineering/posts/2022-4-5-taro-launch/)
Strike announcement 
[Inalienable Property Rights](https://dergigi.com/2022/04/03/inalienable-property-rights/)
Taproot Multisig
Stratum V2
tbDEX

**Comment by louihliu** [comment]
Tesla, Block, and BlockStream

https://www.cnbc.com/2022/04/08/tesla-block-blockstream-to-mine-bitcoin-off-solar-power-in-texas.html

**Comment by kojisanh** [comment]
For the next meetup (5/15), I'd request covering basics of Discrete Log Contract if possible. There is going to be some students attending next time and they seem to be interested in smart contracts and DeFi. DLC should be an interesting topic for those who are not familiar with Bitcoin yet but interested in financial contracts on blockchain.

**Comment by kojisanh** [comment]
(Note: I don't understand DLC well enough to explain  in a simple and easy-to understand way myself, so I need someone else to step up for everyone...)

**Comment by DanGould** [comment]
@kojisanh great idea. The stable contracts on lightning that may be possible with DLCs are of most interest to me. What details do you have on the student's backgrounds and their interest in particular?

https://github.com/discreetlogcontracts/dlcspecs/blob/master/Introduction.md

**Comment by kojisanh** [comment]
They are interested in DeFi(dex, insurance...) so they want to know how does DLC compare to Ethereum style contracts and what tradeoffs it has(scalability, privacy)

**Comment by kojisanh** [comment]
I don't think there are many people who understand even basics of DLC, so going over basic technical concepts with some practical use case examples would be very helpful, I believe.

**Pull request merged**
